// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFvUGaaaB6kgkTHTQE6ZnSk1ASz9waQR0',
    appId: '1:1046852358801:web:0252de90987b61bab5a530',
    messagingSenderId: '1046852358801',
    projectId: 'apula-36cee',
    authDomain: 'apula-36cee.firebaseapp.com',
    storageBucket: 'apula-36cee.firebasestorage.app',
    measurementId: 'G-0EM3HH485S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsfFGULHFFphc_Kk0N4nq19zULnWTyoM',
    appId: '1:1046852358801:android:f7b6226dae06c284b5a530',
    messagingSenderId: '1046852358801',
    projectId: 'apula-36cee',
    storageBucket: 'apula-36cee.firebasestorage.app',
  );
}
