import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

import 'screens/splash_screen.dart';
import 'screens/login/login_screen.dart';
import 'screens/register/register_screen.dart';
import 'screens/app/home/home_page.dart';
import 'screens/register/verification_screen.dart';
import 'screens/register/setpassword_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // ✅ connects your Firebase project
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    const primaryRed = Color(0xFFA30000);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: "Apula",
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: primaryRed,
        ).copyWith(primary: primaryRed, secondary: primaryRed),
      ),
      darkTheme: ThemeData.dark().copyWith(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: primaryRed,
          brightness: Brightness.dark,
        ).copyWith(primary: primaryRed, secondary: primaryRed),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(),
        '/register': (context) => const RegisterScreen(),
        '/home': (context) => const HomePage(),

        // 👇 ADD THESE ROUTES
        '/verification': (context) {
          final email = ModalRoute.of(context)!.settings.arguments as String;
          return VerificationScreen(email: email);
        },
        '/setpassword': (context) {
          final email = ModalRoute.of(context)!.settings.arguments as String;
          return SetPasswordScreen(email: email);
        },
      },
    );
  }
}
